fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BassterMovieDbBundle:
    resource: "@BassterMovieDbBundle/Controller/"
    type:     annotation
    prefix:   /
    
welcome:
    pattern:  /
    defaults: { _controller: BassterMovieDbBundle:Movie:index, capital: null }	

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

